syntax = "proto3";

package rov.telemetry;

// A standard 3-axis representation for IMU data
message Vector3D {
  float x = 1;
  float y = 2;
  float z = 3;
}

// Telemetry from the ROV sensors to the topside
message SensorData {
  uint64 timestamp_us = 1;
  Vector3D acceleration = 2;      // m/s^2
  Vector3D angular_velocity = 3;   // rad/s
  float depth = 4;                 // meters (calculated from pressure)
  float temperature = 5;           // Celsius
}

// testing message
message test {
  string msg = 1;
}

// for tuning
message ControllerTuning {
  bool enable_tuning = 1;
  float k_p = 2;
  float k_i = 3;
  float k_d = 4;
}

message ControllerCommand {
  float x = 1;
  float y = 2;
  float z = 3;
  float roll = 4;
  float pitch = 5;
  float yaw = 6;
  bool enable_depth_control = 7;
  float target_depth = 8;
}
